import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import AuthStatus from "./login/AuthStatus";
import LoginPage from "./login/LoginPage";
import SignupPage from "./login/signup";
import Header from "@/header/Header";
import Footer from "./ES/Footer/page";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <header className="flex justify-center items-center fixed top-0 left-0 w-[1920px] h-[100px] z-30">
          <Header img="logowhite" button="logomenu" />
        </header>
        {children}
        <div style={{ margin: "0" }}>
          <Footer />
        </div>
      </body>
    </html>
  );
}
